// List of forbidden websites
var forbiddenWebsites = [
    "https://www.youtube.com/",
    "https://www.facebook.com/",
    "https://www.instagram.com/",
    "https://www.snapchat.com/",
    "https://web.snapchat.com/",
    "https://www.tiktok.com/",
    "https://www.twitter.com/",
    "https://twitter.com/",
    "https://x.com/",
    "https://www.x.com/",
    "https://www.reddit.com/",
    "https://www.pinterest.com/",
    "https://www.tumblr.com/",
    "https://www.linkedin.com/",
    "https://www.whatsapp.com/",
    "https://web.whatsapp.com/",
    "https://discord.com/",
    "https://discordapp.com/",
    "https://www.messenger.com/",
    "https://www.skype.com/",
    "https://web.skype.com/",
    "https://www.telegram.org/",
    "https://web.telegram.org/",
    "https://www.wechat.com/",
    "https://www.viber.com/",
    "https://www.myspace.com/",
    "https://www.threads.net/",
    "https://www.quora.com/",

    // streaming and video
    "https://www.youtube.com/",
    "https://youtube.com/",
    "https://www.netflix.com/",
    "https://www.hulu.com/",
    "https://www.disneyplus.com/",
    "https://www.hbomax.com/",
    "https://www.primevideo.com/",
    "https://www.peacocktv.com/",
    "https://www.paramountplus.com/",
    "https://www.crunchyroll.com/",
    "https://www.funimation.com/",
    "https://www.twitch.tv/",
    "https://www.vimeo.com/",
    "https://www.dailymotion.com/",
    "https://www.vudu.com/",
    "https://www.tubitv.com/",
    "https://www.plutotv.com/",
    "https://blog.youtube/",
    "https://play.google.com/",
    "http://youtu.be",
    "https://m.youtube.com/",

    // music
    "https://open.spotify.com/",
    "https://www.spotify.com/",
    "https://www.pandora.com/",
    "https://www.apple.com/apple-music/",
    "https://music.amazon.com/",
    "https://soundcloud.com/",
    "https://www.audible.com/",
    "https://www.iheart.com/",
    "https://www.tidal.com/",
    "https://www.deezer.com/",

    // gaming
    "https://www.roblox.com/",
    "https://www.minecraft.net/",
    "https://www.epicgames.com/",
    "https://store.steampowered.com/",
    "https://steamcommunity.com/",
    "https://www.origin.com/",
    "https://www.ea.com/",
    "https://www.ubisoft.com/",
    "https://www.riotgames.com/",
    "https://www.leagueoflegends.com/",
    "https://playvalorant.com/",
    "https://www.callofduty.com/",
    "https://www.xbox.com/",
    "https://www.playstation.com/",
    "https://www.nintendo.com/",
    "https://www.king.com/",
    "https://www.candycrushsaga.com/",
    "https://www.friv.com/",
    "https://www.coolmathgames.com/",
    "https://www.miniclip.com/",
    "https://www.agame.com/",
    "https://www.kongregate.com/",
    "https://www.newgrounds.com/",
    "https://www.armorgames.com/",
    "https://www.y8.com/",
    "https://pokemonshowdown.com/",
    "https://www.chess.com/",
    "https://www.lichess.org/",
    "https://us.shop.battle.net/",
    "https://www.blizzard.com/",
    "https://www.kingdomofloathing.com/",
    "https://www.neopets.com/",
    "https://www.webkinz.com/",
    "https://www.poptropica.com/",
    "https://www.habbo.com/",
    "https://www.guildwars2.com/",
    "https://www.worldofwarcraft.com/",
    "https://www.fortnite.com/",
    "https://www.apexlegends.com/",
    "https://www.overwatch.com/",
    "https://www.destinythegame.com/",

    // shopping and e-commerce
    "https://www.amazon.com/",
    "https://www.ebay.com/",
    "https://www.walmart.com/",
    "https://www.target.com/",
    "https://www.bestbuy.com/",
    "https://www.alibaba.com/",
    "https://www.aliexpress.com/",
    "https://www.shein.com/",
    "https://www.wish.com/",
    "https://www.etsy.com/",
    "https://www.zappos.com/",
    "https://www.asos.com/",
    "https://www.nike.com/",
    "https://www.adidas.com/",
    "https://www.macys.com/",
    "https://www.kohls.com/",
    "https://www.homedepot.com/",
    "https://www.lowes.com/",
    "https://www.wayfair.com/",
    "https://www.overstock.com/",
    "https://www.stockx.com/",

    // dating apps and adult sites
    "https://www.tinder.com/",
    "https://www.bumble.com/",
    "https://www.hinge.com/",
    "https://www.match.com/",
    "https://www.okcupid.com/",
    "https://www.pof.com/",
    "https://help.adultfriendfinder.com/",
    "https://www.pornhub.com/",
    "https://www.xvideos.com/",
    "https://www.XNXX.com/",
    "https://www.redtube.com/",
    "https://www.spankbang.com/",
    "https://www.rule34.com/",
    "https://www.beeg.com/",
    "https://www.8muses.com/"
];

// Make it a window for access in forbidden.js
window.forbiddenWebsites = forbiddenWebsites;
